#!/usr/bin/env sh

if [ -e "${CONFIG_FILE}.template" ]; then
	content=$(cat "${CONFIG_FILE}.template")
	updated_content=$(eval "echo \"$content\"")
	echo "$updated_content" > ${CONFIG_FILE}
	rm ${CONFIG_FILE}.template
fi
