#!/usr/bin/env sh

if [ -e "/www.conf.template" ]; then
	content=$(cat "/www.conf.template")
	updated_content=$(eval "echo \"$content\"")
	echo "$updated_content" > "/etc/php81/php-fpm.d/www.conf"
	rm /www.conf.template
fi
